import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { getUser } from 'service/credentials'
import NavBar from './NavBar'

export default function Layout({ children }) {
  const [user, setUser] = useState('')
  useEffect(() => {
    getUser().then((res) => {
      setUser(res)
    })
  }, [])

  return (
    <>
      <Head>
        <title>UTN</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <NavBar user={user} />
      </div>
      <div className='grid place-items-center '>
        <main>{children}</main>
      </div>
      <style jsx>{`
        main {
          height: 100vh;
          overflow-y: hidden;
          width: 100%;
        }
      `}</style>
    </>
  )
}
