import Head from 'next/head'
import React from 'react'
import NavBar from './NavBar'

export default function Layout({ children, user = '' }) {
  return (
    <>
      <Head>
        <title>UTN</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar user={user} />
      <div className='grid place-items-center h-screen'>
        <main>{children}</main>
      </div>
    </>
  )
}
